lista = [ 'A', 'E', 'I', 'O', 'U' ]
print( lista[0] )
print( lista[1] )
print( lista[2] )
print( lista[-2] )
print( lista[-1] )
print( lista[-5:-2] )
print( lista[2:5] )
print( lista[:2] )
print( lista[2:] )